# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-21 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_annoucement_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoucement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.Course', verbose_name='Curso'),
        ),
    ]
